default: &default
  adapter:  postgresql
  pool:     5
  encoding: unicode

development:
  <<: *default
  database: petrol_price_development

test:
  <<: *default
  database: petrol_price_test

production:
  <<: *default
  database: petrol_price_production
  host: <%= ENV['DATABASE_URL'] %>
